workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods : default
    scripts:
      - name: Install Dependencies
        script: pod install
    artifacts:
      - build/ios/ipa/*.ipa
